import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Builds absolute path
 *
 * An absolute path generated by this function is safer than a relative path as a relative path ends up relative
 * to the current working directory from where the server starts, not relative to the file where path is declared.
 */
export function absolutePath(relativeTo: string, relativePath: string) {
  const __filename = fileURLToPath(relativeTo);
  const __dirname = path.dirname(__filename);

  return path.join(__dirname, relativePath);
}
