import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const paths = {
  apiPublic: absolutePath("./api/public/"),
  database: absolutePath("../database.sqlite"),
  images: absolutePath("../images/"),
  logsApp: absolutePath("../logs/app.log"),
  logsSql: absolutePath("../logs/sql.log"),
  uiBuild: absolutePath("../uiBuild/"),
};

/**
 * Builds absolute path
 *
 * An absolute path generated by this function is safer than a relative path as a relative path ends up relative
 * to the current working directory from where the server starts, not relative to the file where path is declared.
 */
function absolutePath(relativePath: string) {
  return path.join(__dirname, relativePath);
}
